export const html = `<p>As noted in the policy below, the English version of the Privacy Policy and Terms of Use will govern your relationship with Christ Fellowship. You can also view the documents in your language using an automatic translation tool like Google Translate.</p>
<h3>Introduction to Our Privacy Policy</h3>
<p>There are many different ways you can interact online with Christ Fellowship Church, Inc. and our affiliated legal entities ("Christ Fellowship", "we", "us" or "our"), like watching or reading content, being generous through giving, connecting with other people, or taking your next step. We appreciate your interest in our church and respect your privacy as you interact with us online or on our Mobile App.</p>
<p>This Privacy Policy describes how we may treat your information that we have gathered from our websites and applications offered by Christ Fellowship, including <a href="https://christfellowship.church" class="text-ocean hover:text-navy">https://christfellowship.church</a> and any other website, subdomain, mobile-optimized site, or URL that we own or control and that redirects to, or is otherwise associated with, the foregoing (collectively, our "Websites"), and the services and tools related to the Websites (including, but not limited to, mobile and other software applications downloaded from the Websites or obtained elsewhere) (collectively, the "Services").</p>
<p>Please read this Privacy Policy carefully. We did our best to keep the document simple, but if you have any questions about this Privacy Policy or how we use your data, please contact our Data Privacy Team at Christ Fellowship Church, Inc., Attn.: Data Privacy, 5343 Northlake Blvd, Palm Beach Gardens, FL 33418 or at data.privacy@Christfellowship.church</p>
<p>By accessing or using any of our Christ Fellowship sites, you agree to this Privacy Policy and our Terms of Use.</p>
<p>NOTICE REGARDING DISPUTE RESOLUTION: In keeping with 1 Corinthians 6:1-8, all disputes or claims arising under this Privacy Policy, or relating in any way to your use of the Websites, Mobile App, or Services, will be resolved by mediation, and, if not resolved by mediation, then by final and binding arbitration as provided for in Section 9 of our Terms of Use. Unless you opt-out, you will only be able to pursue claims against Christ Fellowship Church, Inc. on an individual basis, not as part of any class or representative action or proceeding, and you will only be permitted to seek relief (including monetary, injunctive, and declaratory relief) on an individual basis.</p>
<h3>Application of Our Privacy Policy</h3>
<p>This Privacy Policy applies only to information collected by the Websites, Mobile Apps, or Services. It does not apply to information either collected by us offline or collected by unaffiliated Websites, Mobile Apps, or Services. Furthermore, this Privacy Policy governs only information provided to and communicated from the Websites, Mobile App, or Services directly and does not govern any other information or communications that may reference this Website, the Services, or Christ Fellowship.</p>
<p>The website analytics-consent controls described below currently apply to <a href="https://christfellowship.church" class="text-ocean hover:text-navy">https://christfellowship.church</a>. Other Websites, mobile applications, giving platforms, and affiliated Services covered by this Policy may use different technologies or present separate notices and controls.</p>
<p>If you click "like" or make a comment on or about Christ Fellowship sites using Facebook, Instagram, Twitter, Pinterest, or other social media plugins, your activity may be published on Facebook, Instagram, Twitter, Pinterest, or other social media website(s), and be shown to other individuals who visit our Websites. We encourage you to read each social media site's respective privacy policy for more information.</p>
<h3>Information We Collect About You and How We Collect It</h3>
<p>Below is an overview of the personal information collected on the Christ Fellowship Websites, Mobile apps, and services and the purpose of our collection. Please note: The processing of your information depends on the information you choose to provide and the functionality of our services you choose to use. A more detailed description of our processing of your information is available below.</p>
<p>Personal Identifiers (name, aliases, Internet Protocol address, email address, phone number, address, and similar identifiers): Collected to the extent you provide it to us to create an account or for association with your account to ensure proper use and authentication for your account. Your personal information is also used to contact you in connection with your requests and account, as discussed in our Privacy Policy.</p>
<p>No mobile information will be shared with third parties or affiliates for marketing or promotional purposes. All the above categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.</p>
<p>Messages from us may incur carrier messaging and data charges. For full SMS program details, including message frequency and how to opt out, see the SMS/Text Messaging Terms in our <a href="https://www.christfellowship.church/terms-of-use" class="text-ocean hover:text-navy">Terms of Use</a>.</p>
<p>Government-Issued Identifications (Social Security numbers, driver's license number, passport numbers, and similar information): Collected and processed to the extent you provide an employment application or to volunteer to do a background check and otherwise process your application.</p>
<p>Financial information (credit card information, banking information, and similar information): Collected to the extent you provide a donation to or purchase merchandise from us in person. Otherwise, financial information provided to us online is processed by third-party service providers, as discussed in our Privacy Policy.</p>
<p>Internet or other network activity (browsing history, search history, information on your interaction with our websites, apps, and other services): Collected as you use our sites and services to monitor and ensure the proper operation of our websites, apps, and services; to improve and customize your experience with regard to the same; to improve, modify, and update our services and content generally, and to analyze the same internally; and provide de-identified statistical information to third parties.</p>
<p>Geolocation data (physical location or movements): Collected if you choose to use the location-based functionality of our services; however, this information is maintained only on your device and is not stored by Christ Fellowship Church.</p>
<p>Professional or employment-related information or non-public educational information: Collected and processed only to the extent you provide an application for employment or volunteer opportunity to do a background check and otherwise process your application.</p>
<p>Sensitive Information (religious information, national origin, sexual orientation, race, marital status, health-related information, genetic information, and similar sensitive data): Your use of our Websites, Mobile apps, and services does not reflect any specific sensitive information, and we do not require that you provide us with the same to use our services. To the extent you choose to provide sensitive information to us through your use of our services, we will process it only with your consent.</p>
<p>Commercial Information (records concerning your personal property, products or services purchased, obtained, or considered, or other purchasing or consuming histories or tendencies): Collected and processed only for purposes of donations and to the extent you provide a donation to or purchase merchandise from us.</p>
<p>Inferences we make about our users based on data available to us. Collected as you use our Websites, Mobile apps, and services to improve and customize your experience with regard to our services and to suggest additional functionality and services.</p>
<h3>How We Use Your Information</h3>
<p>We collect personal data when you provide it, both offline and online. You do not need to provide personal information to use Christ Fellowship websites and services. You can create a profile, which allows us to tailor our sites and services to be a more personalized experience. To create a profile, we require your first and last name, email address, phone number, and password to authenticate you when accessing your profile. Beyond the personal information needed to create a profile, you have choices about what additional information you provide to us, which may include your zip code, the names of family members, gender, and marital status, all of which will be stored in association with your profile. Certain information may be required based on your specific request, such as your social security number for employment inquiries and volunteer requests; we will notify you of this at the time of such a request.</p>
<p>We also collect information about you when you send, receive, or engage in communications with us, including when you submit personal information or requests by emailing hello@christfellowship.church. We retain those communications to process your inquiries, respond to requests, and improve our sites and services.</p>
<p>When you interact with us, the information you provide us is generally stored internally in our third-party relationship management system, or "CRM system." We will use this information to authenticate you and allow you to access your specific profile, when available. We also create user profiles for offline purposes, including volunteerism and inquiries concerning employment. We may combine the information you provide us for your profile and interactions with our websites and mobile apps with the information you provide us through other Christ Fellowship sites, services, and products and inferences we make from the same for our internal development to improve the overall quality of our sites, services, and products. We may also recommend other Christ Fellowship services based on the information you provide, and we infer.</p>
<h3>Your Posts</h3>
<p>Our Christ Fellowship Websites, Mobile apps, and services have a wide array of functionality, including streaming video, creating prayer requests, and identifying and communicating with your Christ Fellowship groups and teams. Some Christ Fellowship Websites, Mobile apps, and services may allow you to publish, distribute, and display content to specific individuals or the public. We will refer to how you provide content and information as "posted" and the content and information posted as "user contributions." User contributions may be made on public areas of websites and social media accounts you access through our sites or may otherwise be transmitted to third parties. Your user contributions are processed by us to facilitate your ability to create, use, store, and distribute user contributions as you choose. We will associate your user contributions with your account if you opt not to delete them.</p>
<p>If you disclose personal information, whether through collaborative postings, social media, message boards, or otherwise, this information may be collected and used by others. User contributions are posted and transmitted at your own risk. We cannot control the actions of other users or third parties with whom you choose to share your user contributions. Therefore, we cannot and do not guarantee that unauthorized persons will not view your user contributions, nor do we accept any liability associated with your user contributions.</p>
<h3>Giving</h3>
<p>If you choose to provide a donation through one of the Christ Fellowship Websites, Mobile apps, and services, then and only then will you be prompted and required to provide a credit card, bank account, and other financial information necessary to process the transaction. We will collect the designation for your donation if you provide one and personal information such as your name, address, phone number, and/or email address to ensure that your donation is used for the purpose you request and to provide you with an annual giving statement that itemizes your donation(s). We will also contact you periodically to inquire if you would like to give to another program, location, or cause. We may contact you through push notifications, SMS, email, mail, or in-app messages to share these opportunities.</p>
<p>This information, excluding your financial information, is stored in our CRM system. As of the date of this Policy, we use PushPay to process your online donation payments made through our Website and Mobile App, except that donations made via Apple Pay within our Mobile App are processed through Stripe. For information on how these third parties process your information, please refer to their privacy policies found here: <a href="https://pushpay.com/legal-center/privacy/" class="text-ocean hover:text-navy">https://pushpay.com/legal-center/privacy/</a> and <a href="https://stripe.com/privacy" class="text-ocean hover:text-navy">https://stripe/privacy.</a></p>
<p>For donations you provide to us in person or by mail, we store your financial information in our databases in an encrypted form for as long as necessary to process your donation and as required by applicable law and GAAP accounting principles.</p>
<h3>Christ Fellowship Merchandise</h3>
<p>For Christ Fellowship sites where you can purchase Christ Fellowship-branded clothing and other items, including our cafe locations, your personal and financial information is provided and shared with our third-party contractors, who will process your order. As of the date of this Policy, we use Square to process these purchases. The third parties are identified at the time of your purchase. For details on how those companies use, store, maintain, and disclose your information, please refer to their respective privacy policies, including <a href="https://squareup.com/us/en/legal/general/privacy-no-account" class="text-ocean hover:text-navy">https://squareup.com/us/en/legal/general/privacy-no-account</a> for Square, or contact them directly.</p>
<h3>Volunteers and Employment Inquiries</h3>
<p>You may apply to volunteer for miscellaneous activities and events in person at a Christ Fellowship location or through one or more of our sites. You may also apply for employment in person and through our sites.</p>
<p>The information we require for volunteer and employment applications are your first and last name, telephone number, address, social security number, date of birth, and your employment history in the case of a job inquiry. We will store and use this information to process your application and associate it with your profile if one exists. We will use your social security number and date of birth solely for a background check regarding your application to be a volunteer and/or employee. We will not share either with any third party except for third-party service providers that enable us to perform background checks. We are obligated not to share or use your information for any other purpose. If you become an employee of Christ Fellowship Church, your personal information is also used in connection with your employment.</p>
<p>As a volunteer, you may have access to third-party software that allows you to schedule and check in to your volunteer activity and manage other volunteer activities. This location-based information is stored in association with your profile to enable you to see your past volunteerism, and we also use it for our internal analysis.</p>
<h3>Automatic Data Collection Technologies</h3>
<p>Our Websites use cookies and similar technologies, including web beacons, pixels, tags, local storage, and device identifiers. Some technologies are necessary to provide requested functionality, maintain security, and remember privacy preferences. Other technologies are optional and help us understand how visitors use our Websites.</p>
<p>On christfellowship.church, optional analytics services are not activated unless you select "Allow analytics" in our cookie-consent banner. You may select "Reject optional" and continue using the Website's necessary features.</p>
<p>Necessary technologies help remember your privacy preference, keep the Website secure, and provide requested functionality. Optional analytics technologies help us understand aggregate usage and improve content and performance. The current website consent configuration does not authorize advertising technologies or interest-based advertising.</p>
<p>Depending on the feature you use and your privacy choices, we may collect information such as pages viewed, links or content selected, searches submitted, browser and device characteristics, IP address, referring and exit pages, timestamps, and approximate location derived from IP address. Mobile application location information is governed by your device permissions and the "WiFi and GPS" section below.</p>
<p>Our mobile applications may use third-party advertising or attribution services, including services associated with Facebook or Google, to measure application downloads or campaign performance. These mobile application practices are separate from the optional website analytics consent used on christfellowship.church. We do not sell personal information or authorize these providers to use personal information to market third-party goods or services to you.</p>
<p>When you allow optional analytics on christfellowship.church, we use Google Tag Manager to load Google Analytics 4 and Microsoft Clarity. These services may receive information such as pages viewed, interactions, browser and device characteristics, IP-derived approximate location, referring pages, and timestamps. Microsoft Clarity may also create session replays and interaction heatmaps; it is configured with masking intended to reduce the collection of text entered into forms.</p>
<p>You can allow or reject optional analytics through the cookie banner and change your choice at any time by selecting "Cookie Settings" in the Website footer. The Website stores your choice locally so it can remember your preference. If you withdraw analytics permission, collection will stop on subsequent page loads in that browser unless you change your choice later. Withdrawing permission does not automatically delete previously collected information; you may contact our Data Privacy Team to request deletion where applicable.</p>
<p>We generally maintain the data we collect from cookies for 21 days but may save it for longer when necessary, such as when required by law or for technical reasons. Although most internet browsers accept cookies by default, you can control cookies through your browser settings and similar tools or agree to refuse all cookies altogether. If you refuse to accept cookies, you may prohibit Christ Fellowship from delivering the full capability of our sites, and you may prevent the use of certain features and services that require these technologies.</p>
<p>Website analytics event data in Google Analytics 4 is currently retained for up to 14 months. Individual cookies, local-storage records, and similar identifiers may have different lifetimes depending on their function. Microsoft Clarity and other service providers retain information according to their service settings and contractual terms. We retain information only for as long as reasonably necessary for the purposes described in this Policy, unless a longer period is required or permitted by law.</p>
<p>We cannot regulate other sites, content, or applications of third parties. They may place their cookies or other files on your computer, collect data, or solicit personal information from you. They may use this information to provide you with interest-based, targeted content. We do not control these third parties' tracking technologies or how they may be used. Contact the responsible provider directly if you have any questions about targeted content.</p>
<h3>WiFi and GPS</h3>
<p>Some of our sites use GPS or wireless ("WiFi") information to identify when you are near one of our physical locations. You can provide consent for us to use this information when you first download or begin to use our sites. If you provide consent, we use the information to enable push notifications related to interactions with our Christ Fellowship sites and physical locations.</p>
<p>You also can manually initiate a location search to identify whether you are at one of our physical locations. When using specific Christ Fellowship sites, you can provide us with your location through your browser, zip code, or city, which a third-party search engine will process. We do not store GPS and WiFi information outside of your device. Once your particular session of use of the feature ends, we will cease access to your GPS and WiFi location unless you use the feature again.</p>
<p>After your first use of this functionality and consent for us to use your GPS or WiFi location, we will assume we have consent unless you revoke it through your mobile device's settings.</p>
<h3>Christ Fellowship Church Content</h3>
<p>We collect how you use the content available through our sites and the language you choose to utilize that content. We process this information to allow you to access and use content through each session of your use of our sites. You can choose whether to download certain Christ Fellowship content to your device. You will have the option to allow Christ Fellowship access to your device's storage to add and modify this downloaded content. Access to the storage of your device is only used by Christ Fellowship for downloading this requested content to your device.</p>
<p>It is your choice whether to create, access, or store Christ Fellowship information and content. If you do, we will store it in association with your profile. We may use information about your use of Christ Fellowship and the inferences we make from that use to provide recommendations to you of other Christ Fellowship content. You may opt out of receiving these recommendations by email, as discussed below.</p>
<h3>Communication From Us to You</h3>
<p>We communicate with you through push notification, SMS/Text messages, phone, email, or in-app messages. If we communicate to you through email, you may unsubscribe to these messages via the unsubscribe and or manage preferences link in the emails providing these messages. You can update your push notification settings at any time within the settings menu of the Christ Fellowship App.</p>
<p>By subscribing, you have provided Christ Fellowship with consent to send you emails and/or SMS/text messages. We use this data to communicate with you about things like events, new content, and requests for volunteer or donation support, and for the other purposes described in this Policy. We do not sell or share this data with third parties for their marketing purposes. Full program details — including message frequency, applicable rates, and how to opt out — are set forth in the SMS/Text Messaging Terms of our <a href="https://www.christfellowship.church/terms-of-use" class="text-ocean hover:text-navy">Terms of Use</a>. You may also withdraw your consent at any time by emailing data.privacy@Christfellowship.church.</p>
<h3>Recommendations and General Information</h3>
<ul>
  <li>We use the data about you and inferences we make from that data to recommend certain content and functionality as well as additional products and services offered by Christ Fellowship.</li>
  <li>We may combine the information you provide with information we collect and the inferences we make for our internal development to improve the overall quality of all services and products provided by Christ Fellowship.</li>
  <li>We may make recommendations to you for other Christ Fellowship services and products based on the information you provide, and we infer.</li>
  <li>We may also use the data we have about you and inferences we make from that data to contact you regarding other opportunities to engage with Christ Fellowship.</li>
  <li>We may contact you through push notification, SMS/Text message, phone, email, mail, or in-app messages to discuss these recommendations and opportunities, how to use our sites, and other news.</li>
</ul>
<h3>Security, Legal, and Technical Issues</h3>
<p>We may use your information to contact you about account security, legal, and other service-related issues. Please be aware that you cannot opt out of receiving such messages from us. We may use your personal information to investigate, respond to, and resolve legal, security, and technical issues and complaints, including, as necessary, security purposes or possible fraud, violations of law or our Terms of Use or this Privacy Policy, or attempts to harm; however, you agree that we have no obligation to prevent or monitor for any of the preceding.</p>
<h3>Notice</h3>
<p>We may use your personal information to provide notice regarding a security incident or data breach by:</p>
<ul>
  <li>sending a message to the email address you provide, as applicable</li>
  <li>posting to a publicly facing page of Christ Fellowship sites or through an in-app messages</li>
  <li>sharing notices through major statewide media and/or telephonic means, including calls and/or text messages, even if sent via automated means including automated dialers.</li>
</ul>
<p>Standard text and data messaging rates may apply from your carrier.</p>
<p>Notices sent by email will be effective when we send the email. Notices we provide by posting will be effective upon posting and by in-app messaging when the message is made. Notices we provide through telephonic means will be effective when transmitted or dialed. You consent to receiving electronic communications from Christ Fellowship relating to your use and access of the services provided by Christ Fellowship. It is your responsibility to keep your email address and any other contact information you provide to us current so that we may provide these communications to you.</p>
<h3>Analytics and Performance</h3>
<p>For christfellowship.church, the optional website analytics described in this section is processed only after a visitor selects "Allow analytics," as explained under "Automatic Data Collection Technologies." Analytics associated with mobile applications, forms, giving, account activity, or other Services may use separate notices or controls.</p>
<p>We internally analyze the personal data available to us, the use of content found on our sites, and the inferences we make from that data to provide and update Christ Fellowship sites, communicate with you, and process information as discussed in this Policy, and for internal analytics such as to observe social, economic, and geographic trends as they pertain to Christ Fellowship content.</p>
<p>In some cases, we work with trusted third parties to perform this research under controls that are designed to protect your privacy as outlined below. For example, we may use your data to generate statistics about overall usage of one of our sites worldwide, in specific geographic regions, or at specific events or locations.</p>
<p>We also use de-identified and aggregate user data to market our sites, including communications that promote growth. Where we publicly share stats of our growth, we analyze and publish the data in an aggregated form, protecting your privacy and keeping your identity and personal information confidential. We use data, including user-provided personal information, aggregations of user data collected through the use of our sites, public feedback, and information inferred from this data to conduct internal research and development in order to provide a better overall experience on Christ Fellowship sites, measure the performance of our sites and increase use of our sites and their features. This is done by making changes to Christ Fellowship sites that are generally available and by sending messages suggesting functionality and content.</p>
<h3>Sensitive Data</h3>
<p>By using Christ Fellowship Church application and sites, we do not assume that you are of any particular religious affiliation or are expressing to us any particular religious belief. We assume you are interested in the content we provide. We do not require users to provide information about such beliefs or any other sensitive data such as race, ethnicity, philosophical beliefs, or physical or mental health to use Christ Fellowship Church sites or create or maintain a Christ Fellowship Church profile.</p>
<p>Some features available through Christ Fellowship Church sites utilize personal information that may reflect your religious or philosophical beliefs, but you are not required to provide such information. In addition to these features, you have control over the content of certain things you create, share, and store through Christ Fellowship Church, and if you provide us with sensitive information with any content you create, share, and store, we will assume we have your consent to process that information.</p>
<p>We will not sell your sensitive personal information, but we may need to share it with third-party service providers that enable us to provide the Christ Fellowship Church sites and/or certain app features and those service providers are required to keep your personal information confidential and only use it to provide us with their services. We will process the sensitive information we collect and inferences we make about the same in accordance with our Privacy Policy and for the purpose of allowing and facilitating your use of those specific app features, to personalize your user experience, suggest other content and services, and internally improve our services.</p>
<p>If you choose to provide any sensitive information to us, we may use that information with other non-sensitive information you provide to create a more personalized Christ Fellowship Church experience for you and to perform the services and actions you request, such as sharing or storing content you create. In any event, Christ Fellowship Church will only process sensitive data you provide to us for Christ Fellowship Church's legitimate activities on your behalf and solely in accordance with the terms of this policy and any additional requests you make about the information. We will also maintain your information subject to appropriate safeguards discussed in this policy and otherwise provided by Christ Fellowship Church.</p>
<p>You have the right to withdraw your consent to our collection and processing of your sensitive personal information by turning off and ceasing to use Christ Fellowship Church features that use this information, or by contacting us via mail at Christ Fellowship Church, Attn.: Data Privacy, 5343 Northlake Blvd, Palm Beach Gardens, FL 33418 or at data.privacy@Christfellowship.church. Withdrawing your consent may hinder our ability to provide certain functionality.</p>
<h3>Disclosure of Your Information</h3>
<p>We do not sell or share your personal data with any third-party advertisers or ad networks for their advertising purposes. We may disclose your personal information to third parties to process information as described above and otherwise enable our ability to provide Christ Fellowship Church, as further discussed below.</p>
<h3>Disclosure on Your Behalf</h3>
<p>We may disclose personal information that we collect, or you provide as described in this Privacy Policy to fulfill our obligations, the purpose for which you provide it, a purpose you request when you provide the information, or any other purpose for which we have your consent.</p>
<h3>Disclosure by You</h3>
<p>If and when you share information through our sites, it is viewable by you and anyone else you choose to share it with. If you give access to your account to other applications and services, based on your approval, those services would have access to your shared information. The use, collection, and protection of your data by such third-party services are subject to those third parties' policies.</p>
<h3>Internal Disclosure</h3>
<p>We will share your personal data internally within Christ Fellowship Church and its affiliates to help combine the personal information covered across the different aspects of Christ Fellowship Church sites and our other products and services to help provide services to you in a manner that is personalized and useful to you and others. For example, we can personalize potential services to recommend to you using cookies or similar technologies that track what functionality you have already opted to receive.</p>
<h3>Service Providers</h3>
<p>We may disclose personal information that we collect or you provide as described in this Privacy Policy to contractors, service providers, and other third parties we use solely to support our sites (such as cloud hosting, cookie providers maintenance, analysis, audit, external marketing, payments, fraud detection, communication, and development), as well as to support our operations (such as communicating with you for potential employment purposes). We may combine the information we have with the information of these service providers to facilitate their support. For example, some of the platforms used to send emails and notifications provided through Christ Fellowship Church are built and managed by third parties, so some of your information is sent securely to those services to provide such functionality. They will have access to your information as reasonably necessary to perform tasks on our behalf and are obligated not to disclose it to others or use it for other purposes. We may also provide aggregate, de-identified information concerning the use of Christ Fellowship Church sites with third parties.</p>
<p>Current providers relevant to the Website disclosures above include Google (tag management and analytics), Microsoft (Clarity analytics), Wistia (video hosting), Algolia (site search), PushPay (giving and payment processing), Stripe (Apple Pay giving processing in our Mobile App), Square (merchandise and cafe purchase processing), and Rock RMS (forms and church-management services). These providers may receive information reasonably necessary to perform their services, subject to applicable agreements and their privacy practices. This list identifies the material providers relevant to these disclosures and is not intended to inventory every software tool used in our operations.</p>
<h3>Content Providers</h3>
<p>We utilize certain third parties to provide content on our sites. We do not share the personal information of users with these third parties. We may provide these third parties with aggregate analytics concerning the use of their content using de-identified and anonymized data.</p>
<p>We use third parties, including Wistia, to provide content on our Websites. These providers may receive technical information needed to deliver content and, where applicable, measure its use. Wistia is configured to use its Privacy Mode, which is intended to limit viewer tracking before a visitor interacts with a video. We do not intentionally provide account-profile information to these providers solely for serving embedded content.</p>
<h3>Legal Process and Subpoena</h3>
<p>We may need to disclose information about you when required by law, subpoena, or other legal process. We attempt to notify users about legal demands for their personal data when appropriate in our judgment, unless prohibited by law or court order or when the request is an emergency. We may dispute such demands when we believe, in our discretion, that the requests are overbroad, vague, or lack proper authority, but we do not promise to challenge every demand. We may also need to disclose your information if we have a good faith belief that disclosure is reasonably necessary to:</p>
<ul>
  <li>Investigate, prevent, or take action regarding suspected or actual illegal activities or to assist government enforcement agencies;</li>
  <li>Enforce our agreements with you;</li>
  <li>Investigate and defend ourselves against any third-party claims or allegations;</li>
  <li>Protect the security or integrity of our sites or</li>
  <li>Exercise or protect the rights and safety of Christ Fellowship Church, our users, personnel, you, or others.</li>
</ul>
<p>We also reserve the right to confidentially disclose personal information we have about you in connection with a potential or actual merger or acquisition such as the sale of all or substantially all our assets.</p>
<h3>Deleting, Accessing, and Correcting Your Information</h3>
<h3>How to Make Your Requests</h3>
<p>For personal data that we have about you, you may request the following:</p>
<p>Deletion: You may ask us to erase or delete all or some of your personal data. Please note that doing so may limit your ability to use certain functionality of Christ Fellowship Church sites. Please note that an email address is required to have an account to ensure we can properly authenticate potential users of that account.</p>
<p>Correction/Modification: You may edit some of your personal data through your account or ask us to change, update, or fix your data in certain cases, including if it is inaccurate.</p>
<p>Object to, or Limit or Restrict, Use of Data: You can ask us to stop using all or some of your personal data or to limit our use of it.</p>
<p>Right to Access and/or Take Your Data: You can ask us for a copy of or disclosure concerning your personal data you provided to us.</p>
<p>Certain laws may provide the right to make additional requests concerning your personal information. If you have provided us with personal information and wish to make such a request under a specific region's law, include the phrase "[Your State/Country] Privacy Request" in the subject line of your request and send your request via email to data.privacy@Christfellowship.church or via mail to Christ Fellowship Church, attn.: Data Privacy, 5343 Northlake Blvd, Palm Beach Gardens, FL 33418.</p>
<p>We ask that individuals making requests identify themselves with at least their name, mailing address, and email address and identify the information requested to be accessed, corrected, or removed before we process the request. We may seek additional information to verify a requestor's identity. We may decline to process requests if we cannot verify the requestor's identity or if we believe the request will jeopardize the privacy of others, violate any law or legal requirement, cause the information to be incorrect, or for a similar legitimate purpose.</p>
<p>We will not discriminate against you for exercising your rights under applicable law. We do not charge a fee to process or respond to a verifiable request concerning your personal information unless it is excessive, unduly burdensome, repetitive, or manifestly unfounded. If we determine that the request warrants a fee, we will tell you why we made that decision and provide a cost estimate before completing your request.</p>
<h3>Deleting Your Account</h3>
<p>You can delete your Christ Fellowship Church account credentials at any time using the settings function in the Christ Fellowship Church application. To request deletion of all account data, you must follow the deletion request instructions above; however, when you delete your account, we will delete the information associated with your account, such as user contributions you have created, received, or shared. If you do not want to delete your account or this information but want to temporarily stop using a Christ Fellowship Church site, you may cease use, and we will maintain your account and the information associated with your account until you resume use or delete your account, whichever comes first.</p>
<p>We generally retain and process information and user contributions associated with your account until your account is deleted. You can manage, change, and delete certain information associated with your account using the Christ Fellowship Church application. If you'd like us to delete your account and all the information associated with your account, you may contact us via email to data.privacy@Christfellowship.church or via mail to Christ Fellowship Church, attn.: Data Privacy, 5343 Northlake Blvd, Palm Beach Gardens, FL 33418.</p>
<p>If you choose to delete your account or ask that we modify or delete personal information, we will delete and purge personal information we have stored about you in a way that is electronically irreversible; however, we may retain your personal data if we have a legal right or obligation to maintain the information or to meet regulatory requirements, resolve disputes, maintain security, prevent fraud and abuse, enforce our rights, or fulfill any other requests from you (for example, to opt-out of further messages or for a copy of your data). Otherwise, if you request that we delete your account, we will delete your account and all the information we have that is associated with your account, except for aggregated statistics based on de-identified information and inferences we have made (for example, the fact that you downloaded our application, without identifying you or maintaining personal information associated with that account).</p>
<p>Our deletion of your information and account will generally take up to 45 days from your request; however, cached information may take up to 30 days to delete. Please note that we have no control of the information you have shared with others through our sites and applications after you close your account, ask to delete information, or attempt to delete your account yourself. Your information and content you have shared may continue to be displayed in the services of others, including search engine results, until their cache refreshes.</p>
<h3>Security and Protection</h3>
<p>We implement security safeguards designed to protect your data. These include using encryption for your data while being transmitted between your device or browser and our servers and while at rest. Data provided to us through our sites is also stored in an ISO 27017-certified infrastructure management system, meaning it has been audited and found in compliance with the requirements of the management system standards ISO 27017, an internationally recognized code of practice for information security controls for cloud services. However, given the nature of communications and information technology and that the use of the internet has inherent risks, although we regularly monitor for possible vulnerabilities and attacks, we cannot warrant or guarantee that information provided to us through our sites or stored in our systems or otherwise will be free from unauthorized intrusion by others, nor can we warrant or guarantee that such data may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards.</p>
<h3>Children</h3>
<p>We do not collect personal information from any person we know is under 13 without the consent of that minor's parent or legal guardian.</p>
<p>A parent or guardian may consent to use our sites or services by a minor. However, we ask that you discuss the risks of sharing personal information on the Internet with your children and require that they refrain from communicating with any third parties or sharing any personal information online or otherwise without the supervision of a parent or guardian. Should you allow your minor child to use our sites or services, you are solely responsible for supervising the minor's use of the same and assume full responsibility for the processing of any information provided to us by that minor.</p>
<p>Where you associate your minor child's information with your account, we will assume you consent to our processing of that information in accordance with this policy and other privacy notices and terms we may provide to you from time to time. If you allow your minor child to use our sites, we ask that you discuss the risks of sharing personal information on the Internet with your children and require that they refrain from communicating with any third parties or sharing any personal information with other users. If you believe we might have any information from or about a child under 13, please contact us at data.privacy@Christfellowship.church.</p>
<h3>Processing of Data</h3>
<p>We will only collect and process your personal data where we have lawful bases. Lawful bases include consent where you have given it, contracts, and other legitimate interests. Such legitimate interests include protection to you, us, other users, and third parties, to comply with applicable law, to enable and administer our internal processes, to manage corporate transactions, to generally understand and improve our internal processes and user experience, and to enable us and other users of our sites to connect with you to exchange information, provided that the preceding adequately protects your rights and freedoms. Where we rely on your consent to process personal data, you have the right to withdraw or decline your consent at any time, and where we rely on legitimate interests, you have the right to object. If you have any questions about the lawful bases upon which we collect and use your personal data, please contact us via email at data.privacy@Christfellowship.church or via mail to Christ Fellowship Church, attn.: Data Privacy, 5343 Northlake Blvd, Palm Beach Gardens, FL 33418.</p>
<h3>Third-Party Information Collection</h3>
<p>This Privacy Policy applies only to sites and apps owned and operated by Christ Fellowship Church. Our sites may contain links to other websites or apps. You are responsible for reviewing the privacy statements and policies of those other websites you choose to link to or from one of our sites so that you can understand how those websites collect, use, and store your information. We are not responsible for the privacy statements, policies or content of other websites or apps, including websites you link to or from a Christ Fellowship Church site. Websites containing co-branding (referencing our name and a third party's name) contain content delivered by the third party, not us.</p>
<p>If you link to other websites, applications, and services or profiles you have with third-party applications, you will provide the personal data stored on those applications to Christ Fellowship Church. For example, you may link your Facebook account to your profile, providing personal information you have opted to share through Facebook to Christ Fellowship Church. When you do so, we are provided with your Facebook or other applicable social media username. You may revoke the link with such accounts and third-party applications by modifying your settings with those applications. As noted above, third-party sites that link to or are associated with our sites may collect information using automated technologies such as cookies. We have no control over such collection and use, which are subject to the privacy policies of those third parties.</p>
<h3>Users Outside the United States</h3>
<p>We are based in Florida within the United States, and the laws of the U.S. and the State of Florida govern your use of our sites and this Privacy Policy. If you are using one of our sites from outside this state or country, your information may be transferred to, stored, and processed in the U.S. where our servers are located, and our central database is operated. We process data both inside and outside of the U.S. and rely on contractual commitments between us and companies transferring personal data that require the protection and security of such data for your privacy. The data protection and other laws of the State of Florida, the U.S., and other countries might not be as comprehensive and may differ from those in your state or country. By using a Christ Fellowship Church site, you consent to your information being transferred to our facilities and to the facilities of those third parties with whom we share it, as described in this Privacy Policy.</p>
<h3>Changes to this Policy</h3>
<p>This Privacy Policy may change from time to time, and your continued use of Christ Fellowship sites after we make changes is deemed to be acceptance of those changes. So, please check this policy periodically for updates. Our policy is to post any changes we make to our Privacy Policy on this page. If we make material changes to how we treat our users' Personal Information, we will notify you by e-mail (if you have an email address on record with us) and through a notice on the website home pages. The date the Privacy Policy was last revised is identified at the top of the page.</p>
<h3>Disputes; Mediation; Arbitration; Waiver of Class Action</h3>
<p>This Privacy Policy is subject to our Terms of Use, including Section 9 of our Terms of Use, which includes mediation and binding arbitration (unless you opt out of arbitration within 60 days of the earlier of your first use of the Websites, Mobile App or Services or registration with the Websites, Mobile App or Services) and a waiver of certain class action rights. Please carefully review these terms, as well as the rest of the Terms of Use, before using our Websites, Mobile Apps or Services.</p>
<h3>Let Us Know How We Are Doing</h3>
<p>We have taken great measures to ensure that your visit to our Websites, Mobile Apps, and Services is a positive experience and that your privacy is constantly respected. If you have any questions, comments, or concerns about our privacy practices, please let us know.</p>
<h3>Contact Information</h3>
<p>To ask questions or comment about this Privacy Policy and our privacy practices, you may contact us at: Christ Fellowship Church.Inc., Attn.: Data Privacy, 5343 Northlake Blvd, Palm Beach Gardens, FL 33418, or at data.privacy@Christfellowship.church.</p>`;
